### ISSUE TITLE
Mesecons texture on button's wall wire not replaced

### ISSUE THREAD

**Issue by BruceMustache** [MysticTempest/REFI_Textures#2]
If you put a button a block and a mesecons you will see the wire is different and the texture isn't at the same style as refi
![refi_report](https://user-images.githubusercontent.com/46538696/88050810-ec800080-cb2d-11ea-9a03-476b7912ea3f.png)

**Comment by MysticTempest** [comment]
Ah okay. Looking into the mesecons modpack; looks like those are receivers.
They don't show up in creative inventory, so I missed them.

Thanks for the heads up; I'll add textures for those in to the next update.

**Comment by MysticTempest** [comment]
Alrighty, added in this commit:
https://github.com/MysticTempest/REFI_Textures/commit/55a581601057a497f91bf293f4c70f2dc15621a0
