### ISSUE TITLE
Dirt texture is too dark...

### ISSUE THREAD

**Issue by barudaret** [MysticTempest/REFI_Textures#4]
...and the dark spots have too many discernible lines/shapes.  The color of plain ol' stone also looks kinda off to me, as if has a hint of violet or something.  These are the only problems I have with this texture pack right now.  I'll try to fix them myself, but I can't make any promises: I am colorblind, so I may end up doing more harm than good.

**Comment by barudaret** [comment]
Nvm about the stone.  My untrustworthy eyes were playing tricks on me.  I have identified a few other issues and I'm working through them.  Fire was too bright, and I've brought that down.  Wheat is too bright, so I'm going to bring that down.  Iron ore needs to be ruddier, because to my eyes, it's pretty much indistinguishable from diamond ore.

**Comment by barudaret** [comment]
Maybe diamond ought to be bluer, too.  It just looks white to me.

**Comment by barudaret** [comment]
Okay, I made a few changes.  Take a look at my fork: https://github.com/barudaret/REFI_Textures and merge anything you like from it.

**Comment by MysticTempest** [comment]
I've been pretty busy, but had some time recently to take a look at this.

The colors aren't bad in terms of any mistake. But, I wasn't too keen on some of the style changes, like dirt, wheat, etc.
However, there was some good ideas here!  


In relation to your comment I did a few tweaks in the latest commit:

1. Darken/desaturate fully-grown wheat a little bit to distinguish from growing wheat.
2. Make iron ore a little pinkish for better viewing in dark areas, but keep classic_grey, as an optional alternate.
3. Make diamond ore, and tools just a little bluer to increase visibility here as well.
------------------

My changes are more on the subtle side to keep the aesthetic of the texture pack pretty consistent.
So you may want to continue using some or all of your custom changes.

But, I appreciate the feedback.
