### ISSUE TITLE
Some brown textures are too greenish

### ISSUE THREAD

**Issue by Ygarr** [MysticTempest/REFI_Textures#5]
Great modpack? I`m usin` it for a long time. But Some brown textures are to green
![screenshot_20211207_041405](https://user-images.githubusercontent.com/14309871/144954117-7c14d9da-6973-4c26-b169-a720a6eb92c2.png)
This color I heard is called marsh,swampy. And things turn out not as they were planned

**Comment by MysticTempest** [comment]
> Great modpack? I`m usin` it for a long time. But Some brown textures are to green -snipped- This color I heard is called marsh,swampy. And things turn out not as they were planned

Hey thanks. 
I'm on a bit of a hiatus from my Minetest projects at the moment. The browns are a light, muddy brown currently; but you can try out these as a temporary alternative.
I color balanced them a little dropping the Green value a bit, and tried to get them a little closer visually; to Dark Brown (#654321).

Download: 
[new_browns.zip](https://github.com/MysticTempest/REFI_Textures/files/7697020/new_browns.zip)

**Comment by MysticTempest** [comment]
Color corrections per my previous comment were officially committed to the repo in the most recent commit: https://github.com/MysticTempest/REFI_Textures/commit/e304d6471d067cb7b778c76fe98988c4cb21e187
