### ISSUE TITLE
upcoming nodebox 2 mesh changes in mcl2

### ISSUE THREAD

**Issue by corarona** [MysticTempest/REFI_Textures#7]
Hey idk if you caught it on the issue tracker so one for you as well:

 just a heads up, we'll probably be changing some(most or even all) nodeboxes to use models/meshes instead. This will sadly require changing the textures in (visually) incompatible ways – Ik the same was done on beds before and I'm sorry that hit everyone by surprise so this time I'll announce it beforehand:

https://git.minetest.land/MineClone2/MineClone2/issues/2996

For the conversion of the cocoa pod there is already a PR which will be in 0.82 according to plan. (0.81 will be released end of this week prob).

ETA for 0.82: after xmas, before new years probably

**Comment by MysticTempest** [comment]
Thanks for the heads up. 
I was aware of the possible cocoa pod PR, but not the plan for other nodes.
That seems a bit excessive. 


But, I guess I'll look into testing alongside any proposed changes. 
I can use something like the following imagemagick commands on my pack; to roughly test out 32px or higher resolutions.
```
find -type f -name "*.png" -exec mogrify -filter point -resize 200% -interpolate Nearest {} \;
```
---

- [ ] Fix cocoa pods
